language: node_js

node_js:
  - '6'
  - '5'
  - '4'
  - '0.12'

before_install:
  - 'npm install -g npm@latest'

cache:
  directories:
  - node_modules

script:
  - npm test

after_success:
    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
